title: Heran's Website
subtitle: Make a dent in the universe.
author: linhr

permalink: /:categories/:year/:month/:day/:title/
timezone: Etc/UTC
baseurl: 
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - sass
  - config.rb

markdown: redcarpet
pygments: true
