title: Heran's Website
subtitle: Make a dent in the universe.
author: linhr

permalink: /:categories/:year/:month/:day/:title/
timezone: Asia/Shanghai
baseurl: 
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - sass
  - config.rb

markdown: redcarpet
pygments: true

google_analytics:
  tracking_id: 'UA-46149677-1'
  cookie_domain: 'linhr.me'