title: Heran Lin
subtitle: Code and love.
author: linhr

permalink: /:categories/:title/
timezone: Asia/Shanghai
baseurl: 
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - sass
  - config.rb

markdown: redcarpet
highlighter: pygments

google_analytics:
  tracking_id: 'UA-46149677-1'
  cookie_domain: 'linhr.me'
